---
title: "End-of-class student presentations"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

During our last class, we want to give you all the opportunity to share ideas about how the skills we've learned in this course can be applied in practice. 

We would like each of you to give a *very brief* presentation showing the rest of the class either

a) One or several ways in which you have already implemented something from the class in your own work, or 

a) An overview of changes you plan to make in your workflow moving forward.

Please get as concrete as possible; don't just talk in general terms, but pull up RStudio or GitHub and show us some new code you've been writing in tidyverse, the nice GitHub repo you've created for one of your projects, or maybe even the new website you've set up. Alternatively, if you're using open science tools or strategies that we haven't covered in class, but you think could be of interest to others, feel free to focus on those.  

**When:** Thursday March 30 2023 during class  
**How long:** 1.5 minutes per student  
**What to show:** You can share your screen through the Zoom call to either a) do a live demo showing a GitHub repo, something you've been working on in RStudio, a website, or whatever way you either have applied or that you're thinking about applying something from the course, or b) show a slide that summarizes what you think are the most useful thing(s) you have learned in the course and how this will help you in the future.  
**Who should do it:** A presentation is required from all students taking the course for credit. If you can't make it to the live Zoom call, you can submit a video instead (due before class on March 30). Auditors are also welcome to contribute if they would like to share with the class.  


